// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	overtime "github.com/riskykurniawan15/payrolls/models/overtime"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockIOvertimeRepository is an autogenerated mock type for the IOvertimeRepository type
type MockIOvertimeRepository struct {
	mock.Mock
}

type MockIOvertimeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIOvertimeRepository) EXPECT() *MockIOvertimeRepository_Expecter {
	return &MockIOvertimeRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *MockIOvertimeRepository) Create(ctx context.Context, _a1 *overtime.Overtime) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *overtime.Overtime) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIOvertimeRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIOvertimeRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *overtime.Overtime
func (_e *MockIOvertimeRepository_Expecter) Create(ctx interface{}, _a1 interface{}) *MockIOvertimeRepository_Create_Call {
	return &MockIOvertimeRepository_Create_Call{Call: _e.mock.On("Create", ctx, _a1)}
}

func (_c *MockIOvertimeRepository_Create_Call) Run(run func(ctx context.Context, _a1 *overtime.Overtime)) *MockIOvertimeRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*overtime.Overtime))
	})
	return _c
}

func (_c *MockIOvertimeRepository_Create_Call) Return(_a0 error) *MockIOvertimeRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIOvertimeRepository_Create_Call) RunAndReturn(run func(context.Context, *overtime.Overtime) error) *MockIOvertimeRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockIOvertimeRepository) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIOvertimeRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIOvertimeRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockIOvertimeRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockIOvertimeRepository_Delete_Call {
	return &MockIOvertimeRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockIOvertimeRepository_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockIOvertimeRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockIOvertimeRepository_Delete_Call) Return(_a0 error) *MockIOvertimeRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIOvertimeRepository_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *MockIOvertimeRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockIOvertimeRepository) GetByID(ctx context.Context, id uint) (*overtime.Overtime, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *overtime.Overtime
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*overtime.Overtime, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *overtime.Overtime); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*overtime.Overtime)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOvertimeRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockIOvertimeRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockIOvertimeRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockIOvertimeRepository_GetByID_Call {
	return &MockIOvertimeRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockIOvertimeRepository_GetByID_Call) Run(run func(ctx context.Context, id uint)) *MockIOvertimeRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockIOvertimeRepository_GetByID_Call) Return(_a0 *overtime.Overtime, _a1 error) *MockIOvertimeRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOvertimeRepository_GetByID_Call) RunAndReturn(run func(context.Context, uint) (*overtime.Overtime, error)) *MockIOvertimeRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserAndDateRange provides a mock function with given fields: ctx, userID, startDate, endDate
func (_m *MockIOvertimeRepository) GetByUserAndDateRange(ctx context.Context, userID uint, startDate time.Time, endDate time.Time) ([]overtime.Overtime, error) {
	ret := _m.Called(ctx, userID, startDate, endDate)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserAndDateRange")
	}

	var r0 []overtime.Overtime
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, time.Time, time.Time) ([]overtime.Overtime, error)); ok {
		return rf(ctx, userID, startDate, endDate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, time.Time, time.Time) []overtime.Overtime); ok {
		r0 = rf(ctx, userID, startDate, endDate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]overtime.Overtime)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, time.Time, time.Time) error); ok {
		r1 = rf(ctx, userID, startDate, endDate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOvertimeRepository_GetByUserAndDateRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserAndDateRange'
type MockIOvertimeRepository_GetByUserAndDateRange_Call struct {
	*mock.Call
}

// GetByUserAndDateRange is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - startDate time.Time
//   - endDate time.Time
func (_e *MockIOvertimeRepository_Expecter) GetByUserAndDateRange(ctx interface{}, userID interface{}, startDate interface{}, endDate interface{}) *MockIOvertimeRepository_GetByUserAndDateRange_Call {
	return &MockIOvertimeRepository_GetByUserAndDateRange_Call{Call: _e.mock.On("GetByUserAndDateRange", ctx, userID, startDate, endDate)}
}

func (_c *MockIOvertimeRepository_GetByUserAndDateRange_Call) Run(run func(ctx context.Context, userID uint, startDate time.Time, endDate time.Time)) *MockIOvertimeRepository_GetByUserAndDateRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(time.Time), args[3].(time.Time))
	})
	return _c
}

func (_c *MockIOvertimeRepository_GetByUserAndDateRange_Call) Return(_a0 []overtime.Overtime, _a1 error) *MockIOvertimeRepository_GetByUserAndDateRange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOvertimeRepository_GetByUserAndDateRange_Call) RunAndReturn(run func(context.Context, uint, time.Time, time.Time) ([]overtime.Overtime, error)) *MockIOvertimeRepository_GetByUserAndDateRange_Call {
	_c.Call.Return(run)
	return _c
}

// GetTotalHoursByUserAndDate provides a mock function with given fields: ctx, userID, date
func (_m *MockIOvertimeRepository) GetTotalHoursByUserAndDate(ctx context.Context, userID uint, date time.Time) (float64, error) {
	ret := _m.Called(ctx, userID, date)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalHoursByUserAndDate")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, time.Time) (float64, error)); ok {
		return rf(ctx, userID, date)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, time.Time) float64); ok {
		r0 = rf(ctx, userID, date)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, time.Time) error); ok {
		r1 = rf(ctx, userID, date)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOvertimeRepository_GetTotalHoursByUserAndDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTotalHoursByUserAndDate'
type MockIOvertimeRepository_GetTotalHoursByUserAndDate_Call struct {
	*mock.Call
}

// GetTotalHoursByUserAndDate is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - date time.Time
func (_e *MockIOvertimeRepository_Expecter) GetTotalHoursByUserAndDate(ctx interface{}, userID interface{}, date interface{}) *MockIOvertimeRepository_GetTotalHoursByUserAndDate_Call {
	return &MockIOvertimeRepository_GetTotalHoursByUserAndDate_Call{Call: _e.mock.On("GetTotalHoursByUserAndDate", ctx, userID, date)}
}

func (_c *MockIOvertimeRepository_GetTotalHoursByUserAndDate_Call) Run(run func(ctx context.Context, userID uint, date time.Time)) *MockIOvertimeRepository_GetTotalHoursByUserAndDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(time.Time))
	})
	return _c
}

func (_c *MockIOvertimeRepository_GetTotalHoursByUserAndDate_Call) Return(_a0 float64, _a1 error) *MockIOvertimeRepository_GetTotalHoursByUserAndDate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOvertimeRepository_GetTotalHoursByUserAndDate_Call) RunAndReturn(run func(context.Context, uint, time.Time) (float64, error)) *MockIOvertimeRepository_GetTotalHoursByUserAndDate_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, req, userID
func (_m *MockIOvertimeRepository) List(ctx context.Context, req overtime.ListOvertimesRequest, userID uint) (*overtime.ListOvertimesResponse, error) {
	ret := _m.Called(ctx, req, userID)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *overtime.ListOvertimesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, overtime.ListOvertimesRequest, uint) (*overtime.ListOvertimesResponse, error)); ok {
		return rf(ctx, req, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, overtime.ListOvertimesRequest, uint) *overtime.ListOvertimesResponse); ok {
		r0 = rf(ctx, req, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*overtime.ListOvertimesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, overtime.ListOvertimesRequest, uint) error); ok {
		r1 = rf(ctx, req, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOvertimeRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockIOvertimeRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - req overtime.ListOvertimesRequest
//   - userID uint
func (_e *MockIOvertimeRepository_Expecter) List(ctx interface{}, req interface{}, userID interface{}) *MockIOvertimeRepository_List_Call {
	return &MockIOvertimeRepository_List_Call{Call: _e.mock.On("List", ctx, req, userID)}
}

func (_c *MockIOvertimeRepository_List_Call) Run(run func(ctx context.Context, req overtime.ListOvertimesRequest, userID uint)) *MockIOvertimeRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(overtime.ListOvertimesRequest), args[2].(uint))
	})
	return _c
}

func (_c *MockIOvertimeRepository_List_Call) Return(_a0 *overtime.ListOvertimesResponse, _a1 error) *MockIOvertimeRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOvertimeRepository_List_Call) RunAndReturn(run func(context.Context, overtime.ListOvertimesRequest, uint) (*overtime.ListOvertimesResponse, error)) *MockIOvertimeRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, updates
func (_m *MockIOvertimeRepository) Update(ctx context.Context, id uint, updates map[string]interface{}) error {
	ret := _m.Called(ctx, id, updates)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, map[string]interface{}) error); ok {
		r0 = rf(ctx, id, updates)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIOvertimeRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIOvertimeRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
//   - updates map[string]interface{}
func (_e *MockIOvertimeRepository_Expecter) Update(ctx interface{}, id interface{}, updates interface{}) *MockIOvertimeRepository_Update_Call {
	return &MockIOvertimeRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, updates)}
}

func (_c *MockIOvertimeRepository_Update_Call) Run(run func(ctx context.Context, id uint, updates map[string]interface{})) *MockIOvertimeRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockIOvertimeRepository_Update_Call) Return(_a0 error) *MockIOvertimeRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIOvertimeRepository_Update_Call) RunAndReturn(run func(context.Context, uint, map[string]interface{}) error) *MockIOvertimeRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIOvertimeRepository creates a new instance of MockIOvertimeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIOvertimeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIOvertimeRepository {
	mock := &MockIOvertimeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
